import { StyleSheet } from "react-native";

/**
 * Archivo centralizado de estilos para las distintas pantallas de la
 * aplicación. Aquí se separan las definiciones de estilos del código
 * principal de cada componente, permitiendo una gestión unificada de
 * colores, tamaños y espaciados. Cada objeto exportado corresponde
 * aproximadamente a los estilos originales definidos en los archivos de
 * pantalla.
 */

// === Estilos para la pantalla de inicio de sesión ===
export const loginStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F1F8E9", // Fondo verde muy suave (toque ambiental)
  },
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "center",
    paddingBottom: 20,
  },
  // === LOGO ===
  logoContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoEnviro: {
    fontSize: 38,
    fontWeight: "800",
    color: "#2E7D32",
    letterSpacing: 0.5,
  },
  logoClean: {
    fontSize: 38,
    fontWeight: "800",
    color: "#1565C0",
    letterSpacing: 0.5,
  },
  tagline: {
    fontSize: 13,
    color: "#546E7A",
    marginTop: 4,
    fontWeight: "500",
    textAlign: "center",
  },
  welcome: {
    fontSize: 26,
    fontWeight: "700",
    color: "#212121",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 15,
    color: "#616161",
    textAlign: "center",
    marginBottom: 28,
  },
  // === TARJETA DEL FORMULARIO ===
  formCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 26,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E0E0E0",
    borderRadius: 14,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: "#212121",
    paddingVertical: 15,
  },
  eyeButton: {
    padding: 6,
    marginLeft: 8,
  },
  forgotContainer: {
    alignSelf: "flex-end",
    marginBottom: 22,
  },
  forgotText: {
    color: "#2E7D32",
    fontSize: 14,
    fontWeight: "600",
  },
  button: {
    backgroundColor: "#2E7D32",
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: "#2E7D32",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
  },
  footer: {
    textAlign: "center",
    color: "#9E9E9E",
    fontSize: 12,
    marginTop: 40,
  },
});

// === Estilos para la pantalla del cliente ===
export const clientStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F1F8E9",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 10,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1B5E20",
  },
  subtitle: {
    fontSize: 14,
    color: "#555",
    marginTop: 2,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginRight: 8,
  },
  logoutText: {
    color: "#c62828",
    fontWeight: "600",
  },
  container: {
    paddingHorizontal: 20,
    paddingBottom: 50,
  },
  welcomeCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  welcomeIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#E8F5E9",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  welcomeTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1B5E20",
    marginBottom: 8,
  },
  welcomeText: {
    fontSize: 15,
    color: "#555",
    textAlign: "center",
    lineHeight: 22,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1B5E20",
    marginBottom: 10,
  },
  cardDescription: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    marginBottom: 16,
  },
  mainActionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
    marginBottom: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  mainActionIconBlue: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
  },
  mainActionIconOrange: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#FFF3E0",
    justifyContent: "center",
    alignItems: "center",
  },
  actionContent: {
    flex: 1,
  },
  mainActionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#333",
    marginBottom: 3,
  },
  mainActionSubtitle: {
    fontSize: 13,
    color: "#666",
    lineHeight: 18,
  },
  topActionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 10,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#C8E6C9",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 6,
  },
  backButtonText: {
    color: "#1B5E20",
    fontWeight: "700",
  },
  refreshButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2E7D32",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 6,
  },
  refreshButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  emptyCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 16,
    padding: 22,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#555",
    marginTop: 10,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    color: "#777",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 14,
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    gap: 6,
  },
  secondaryButtonText: {
    color: "#2E7D32",
    fontWeight: "700",
  },
  recordCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    marginBottom: 12,
    overflow: "hidden",
  },
  recordHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
  },
  recordTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1B5E20",
    marginBottom: 4,
  },
  recordSubtitle: {
    fontSize: 13,
    color: "#666",
    marginBottom: 3,
  },
  recordService: {
    fontSize: 13,
    color: "#333",
    fontWeight: "600",
  },
  recordDetails: {
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  infoRow: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  infoLabel: {
    fontSize: 12,
    color: "#777",
    fontWeight: "700",
    marginBottom: 3,
  },
  infoValue: {
    fontSize: 14,
    color: "#333",
  },
  stationCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  stationHeader: {
    marginBottom: 12,
  },
  stationBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#1B5E20",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 8,
  },
  stationBadgeText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  stationLocation: {
    fontSize: 14,
    color: "#555",
    fontWeight: "600",
  },
  photoItem: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  photoItemNoConforme: {
    borderColor: "#ef9a9a",
    backgroundColor: "#fffafa",
  },
  photoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
    gap: 10,
  },
  photoLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: "#333",
  },
  photoBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    gap: 4,
  },
  photoBadgeText: {
    color: "#2E7D32",
    fontSize: 12,
    fontWeight: "700",
  },
  photoBadgeGray: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F1F1F1",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    gap: 4,
  },
  photoBadgeGrayText: {
    color: "#777",
    fontSize: 12,
    fontWeight: "700",
  },
  noConformeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#c62828",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    gap: 4,
  },
  noConformeBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },
  photoThumbnail: {
    width: "100%",
    height: 150,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: "#eee",
  },
  photoDate: {
    color: "#666",
    fontSize: 13,
  },
  noPhotoBox: {
    height: 110,
    borderRadius: 12,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    padding: 12,
  },
  noPhotoText: {
    color: "#888",
    fontSize: 13,
    marginTop: 6,
    textAlign: "center",
  },
  recordSelectorList: {
    gap: 10,
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: "#333",
    marginBottom: 10,
  },
  recordSelectorItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  recordSelectorItemSelected: {
    backgroundColor: "#2E7D32",
    borderColor: "#2E7D32",
  },
  recordSelectorTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#333",
    marginBottom: 3,
  },
  recordSelectorTitleSelected: {
    color: "#fff",
  },
  recordSelectorSubtitle: {
    fontSize: 12,
    color: "#666",
  },
  recordSelectorSubtitleSelected: {
    color: "#E8F5E9",
  },
  incidentSummary: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF3E0",
    padding: 12,
    borderRadius: 12,
    marginBottom: 14,
    gap: 8,
  },
  incidentSummaryText: {
    color: "#E65100",
    fontWeight: "800",
  },
  noConformeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ffcdd2",
    borderRadius: 12,
    paddingVertical: 11,
    gap: 7,
  },
  noConformeButtonOn: {
    backgroundColor: "#c62828",
    borderColor: "#c62828",
  },
  noConformeButtonText: {
    color: "#c62828",
    fontWeight: "800",
  },
  noConformeButtonTextOn: {
    color: "#fff",
  },
  inputGroupLarge: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingTop: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  inputIcon: {
    marginRight: 10,
  },
  textAreaHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  textAreaLabel: {
    color: "#333",
    fontSize: 15,
    fontWeight: "700",
  },
  textArea: {
    minHeight: 120,
    fontSize: 16,
    color: "#222",
    textAlignVertical: "top",
    paddingBottom: 12,
  },
  saveIncidentBtn: {
    backgroundColor: "#c62828",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: 16,
    marginTop: 8,
  },
  saveIncidentText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  previewModal: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  previewClose: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
  },
  previewImage: {
    width: "100%",
    height: "70%",
  },
  previewInfo: {
    marginTop: 20,
    alignItems: "center",
  },
  previewDate: {
    color: "#fff",
    fontSize: 15,
    marginBottom: 6,
  },
  previewGps: {
    color: "#ccc",
    fontSize: 14,
  },
});

// === Estilos para la pantalla de administración ===
export const adminStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F1F8E9" },
  container: { padding: 20, paddingBottom: 40 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  title: { fontSize: 26, fontWeight: "800", color: "#1B5E20" },
  subtitle: { color: "#555", fontSize: 15, marginTop: 2 },
  logoutBtn: { flexDirection: "row", alignItems: "center", gap: 6 },
  logoutText: { color: "#c62828", fontWeight: "600" },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    width: "47%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderLeftWidth: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  statLabel: { fontSize: 13, color: "#666", marginTop: 6 },
  statNumber: { fontSize: 26, fontWeight: "800", color: "#222", marginTop: 2 },
  primaryBtn: {
    backgroundColor: "#2E7D32",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 14,
    marginBottom: 24,
    shadowColor: "#2E7D32",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  primaryBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B5E20",
    marginBottom: 12,
  },
  permissionsCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 8,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  permissionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  permissionInfo: { flexDirection: "row", alignItems: "center", gap: 10 },
  permissionText: { fontSize: 15, color: "#333" },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  count: { color: "#666", fontSize: 14 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  cardWrapper: { width: "47%" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#222",
    flex: 1,
    marginRight: 8,
  },
  cardSubtitle: { color: "#555", fontSize: 13, marginBottom: 12 },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  meta: { fontSize: 12, color: "#888" },
  badge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 20 },
  badgeGreen: { backgroundColor: "#C8E6C9" },
  badgeOrange: { backgroundColor: "#FFE0B2" },
  badgeRed: { backgroundColor: "#FFCDD2" },
  badgeText: { fontSize: 11, fontWeight: "700" },
  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyText: { color: "#999", marginTop: 12 },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: { backgroundColor: "#fff", borderRadius: 20, padding: 24 },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 20,
    color: "#1B5E20",
  },
  input: {
    borderWidth: 1.5,
    borderColor: "#ddd",
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    marginBottom: 16,
  },
  label: { fontSize: 14, color: "#555", marginBottom: 8 },
  roleRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  roleBtn: {
    flex: 1,
    padding: 12,
    borderWidth: 1.5,
    borderColor: "#ddd",
    borderRadius: 12,
    alignItems: "center",
  },
  roleActive: { backgroundColor: "#C8E6C9", borderColor: "#2E7D32" },
  roleText: { color: "#555" },
  roleActiveText: { color: "#1B5E20", fontWeight: "600" },
  cancelText: { textAlign: "center", color: "#c62828", fontWeight: "600" },
  // Detalle
  detailContainer: { padding: 20 },
  detailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  detailTitle: { fontSize: 22, fontWeight: "800", color: "#1B5E20" },
  infoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    marginBottom: 20,
  },
  infoRow: { marginBottom: 14 },
  infoLabel: { fontSize: 13, color: "#666", marginBottom: 4 },
  infoValue: { fontSize: 16, fontWeight: "600", color: "#222" },
  gpsCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
  },
  gpsTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 10,
    color: "#1565C0",
  },
  mapButton: {
    marginTop: 12,
    backgroundColor: "#2E7D32",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  mapButtonText: { color: "#fff", fontWeight: "700" },
  stationCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  stationTitle: { fontSize: 17, fontWeight: "700", marginBottom: 12 },
  photoSection: { marginBottom: 16 },
  photoLabel: {
    fontSize: 14,
    color: "#555",
    marginBottom: 6,
    fontWeight: "600",
  },
  photo: { width: "100%", height: 180, borderRadius: 12 },
  closeButton: {
    backgroundColor: "#333",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 40,
  },
  closeButtonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
});

// === Estilos centralizados adicionales ===

/**
 * Estilos para la pantalla principal del trabajador (menú).
 * Se utiliza en `src/app/worker/index.tsx`.
 */
export const workerMenuStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F1F8E9",
    padding: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#1B5E20",
    textAlign: "center",
  },
  subtitle: {
    textAlign: "center",
    color: "#666",
    marginBottom: 20,
  },
  wrapper: {
    marginTop: 20,
    gap: 14,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  cardText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#222",
  },
});

/**
 * Estilos para la pantalla de historial del trabajador.
 * Se utiliza en `src/app/worker/history.tsx`.
 */
export const workerHistoryStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F1F8E9",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
    alignItems: "center",
  },
  title: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1B5E20",
  },
  subtitle: {
    fontSize: 13,
    color: "#555",
  },
  logoutBtn: {
    padding: 8,
  },
  loading: {
    paddingHorizontal: 16,
    color: "#1565C0",
    fontWeight: "600",
  },
  card: {
    backgroundColor: "#fff",
    margin: 12,
    padding: 16,
    borderRadius: 16,
    elevation: 3,
  },
  rowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  client: {
    fontSize: 16,
    fontWeight: "700",
  },
  badge: {
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeText: {
    color: "#1B5E20",
    fontWeight: "700",
    fontSize: 12,
  },
  line: {
    fontSize: 13,
    color: "#444",
    marginTop: 4,
  },
  date: {
    fontSize: 12,
    color: "#666",
    marginTop: 6,
  },
  stationCard: {
    marginTop: 14,
    padding: 12,
    backgroundColor: "#FAFAFA",
    borderRadius: 12,
  },
  stationTitle: {
    fontWeight: "700",
    marginBottom: 8,
  },
  photoBox: {
    marginBottom: 10,
  },
  photoLabel: {
    fontSize: 12,
    color: "#555",
    marginBottom: 4,
  },
  photo: {
    width: "100%",
    height: 160,
    borderRadius: 10,
  },
  emptyCard: {
    padding: 20,
    margin: 20,
    backgroundColor: "#fff",
    borderRadius: 14,
    alignItems: "center",
  },
  emptyText: {
    color: "#777",
  },
});

/**
 * Estilos para la pantalla de formulario del trabajador.
 * Se utiliza en `src/app/worker/form.tsx`.
 */
export const workerFormStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F1F8E9",
  },
  container: {
    padding: 20,
    paddingBottom: 50,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1B5E20",
  },
  subtitle: {
    color: "#555",
    fontSize: 14,
    marginTop: 2,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginRight: 18,
    marginTop: 4,
  },
  logoutText: {
    color: "#c62828",
    fontWeight: "600",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B5E20",
    marginBottom: 16,
  },
  counterBadge: {
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  counterBadgeText: {
    color: "#1B5E20",
    fontWeight: "800",
  },
  inputGroup: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 14,
    color: "#222",
  },
  inputGroupLarge: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingTop: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  textAreaHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  textAreaLabel: {
    color: "#333",
    fontSize: 15,
    fontWeight: "600",
  },
  textArea: {
    minHeight: 130,
    fontSize: 16,
    color: "#222",
    textAlignVertical: "top",
    paddingBottom: 12,
  },
  selectorBox: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  selectorHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  selectorLabel: {
    color: "#333",
    fontSize: 15,
    fontWeight: "700",
  },
  selectorValue: {
    color: "#222",
    fontSize: 16,
    marginBottom: 10,
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  optionBtn: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#C8E6C9",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  optionBtnSelected: {
    backgroundColor: "#2E7D32",
    borderColor: "#2E7D32",
  },
  optionText: {
    color: "#2E7D32",
    fontWeight: "700",
  },
  optionTextSelected: {
    color: "#fff",
  },
  readOnlyField: {
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    marginBottom: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#C8E6C9",
  },
  readOnlyHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  readOnlyLabel: {
    color: "#1B5E20",
    fontSize: 15,
    fontWeight: "700",
  },
  readOnlyText: {
    color: "#1B5E20",
    fontSize: 16,
    fontWeight: "800",
  },
  stationCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  stationTopBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#1B5E20",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 12,
  },
  stationTopBadgeText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  emptyBox: {
    backgroundColor: "#FAFAFA",
    borderRadius: 14,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  emptyText: {
    color: "#777",
    marginTop: 8,
    textAlign: "center",
  },
  photoItem: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  photoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
    gap: 10,
  },
  photoLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: "#333",
  },
  photoBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    gap: 4,
  },
  photoBadgeText: {
    color: "#2E7D32",
    fontSize: 12,
    fontWeight: "600",
  },
  takePhotoBtn: {
    backgroundColor: "#2E7D32",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  takePhotoText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  photoThumbnail: {
    width: "100%",
    height: 140,
    borderRadius: 12,
    marginBottom: 10,
  },
  photoActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    backgroundColor: "#F5F5F5",
    borderRadius: 10,
  },
  actionTextBlue: {
    color: "#1565C0",
    fontWeight: "600",
  },
  actionTextRed: {
    color: "#c62828",
    fontWeight: "600",
  },
  saveBtn: {
    backgroundColor: "#1B5E20",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 16,
    marginTop: 10,
    shadowColor: "#1B5E20",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
  },
  clearBtn: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ffcdd2",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 12,
  },
  clearBtnText: {
    color: "#c62828",
    fontSize: 16,
    fontWeight: "700",
  },
  cameraOverlay: {
    position: "absolute",
    bottom: 50,
    width: "100%",
    alignItems: "center",
  },
  cameraCancel: {
    position: "absolute",
    top: -620,
    right: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: 10,
    borderRadius: 30,
  },
  captureBtn: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  captureInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#2E7D32",
  },
  cameraHint: {
    color: "#fff",
    marginTop: 16,
    fontSize: 14,
  },
  previewModal: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  previewClose: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
  },
  previewImage: {
    width: "100%",
    height: "70%",
  },
  previewInfo: {
    marginTop: 20,
    alignItems: "center",
  },
  previewDate: {
    color: "#fff",
    fontSize: 15,
    marginBottom: 6,
  },
  previewGps: {
    color: "#ccc",
    fontSize: 14,
  },
});